<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevConfTicketing.Domain\DevConfTicketing.Domain.csproj" />
    <ProjectReference Include="..\DevConfTicketing.Application\DevConfTicketing.Application.csproj" />
  </ItemGroup>

</Project>
