using '../main.bicep'

param environmentName = 'prod'
param location = 'germanywestcentral'
param containerAppsEnvironmentName = 'nrwdevconf-env'
param managedIdentityName = 'nrwdevconf_mi'
param keyVaultName = 'nrwdevconf'
param logAnalyticsWorkspaceName = 'nrwdevconflogs'
param acrName = 'siaconsulting'
param acrResourceGroup = 'sia-consulting'
param acrLoginServer = 'siaconsulting.azurecr.io'
param cosmosDbAccountName = 'devconf-ticketing-db'
param appInsightsName = 'devconf-ticketing-insights'
param backendAppName = 'devconf-ticketing-api'
param frontendAppName = 'devconf-ticketing-frontend'
param imageTag = 'latest'
param entraIdTenantId = ''
param entraIdClientId = ''
param entraIdAudience = 'api://devconf-ticketing'
